### ISSUE TITLE
rosdep on undefined key 'blas'

### ISSUE THREAD

**Issue by tfoote** [ethz-asl/ceres_catkin#30]
I was working with this package in a workspace and invoked `rosdep install` with the `--from-path` option and it could not resolve the `blas` rosdep key. 

There's a similar rule here: https://github.com/ros/rosdistro/blob/master/rosdep/base.yaml#L1300-L1304

And there's Atlas: https://github.com/ros/rosdistro/blob/master/rosdep/base.yaml#L200 which is also a dependency. 

It successfully built after running `rosdep install --from-path . -iy --skip-keys blas` which suggests that this dependency declaration might be unnecessary.

**Comment by schneith** [comment]
Thanks for the report.

It seems that ceres requires ATLAS and optionally LAPACK/BLAS (http://ceres-solver.org/building.html#dependencies). I have update the dependency keys to fix the rosdep lookup.

**Comment by tfoote** [comment]
Great thanks!
